// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxaxqyxkejjuzkhaxkpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4YXhxeXhrZWpqdXpraGF4a3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDU4OTksImV4cCI6MjA2Njc4MTg5OX0.BiHKpch89YyFkcBFMqnFLIlSoSnehiFl5nHum5KSgKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});